2.3.1-release
tiktok/tiktok-opensdk-android pull request #38
Opened 2024-10-24 00:10 UTC by CaballoMa-Tiktok

change redirect_uri from deeplink to https

2024-10-24 19:45 UTC, haifano approved these changes

2024-10-24 20:35 UTC, merged

2024-12-27 17:35 UTC, samuel-YH approved these changes

2025-01-07 08:30 UTC, fockmoney requested changes
How to used conis fake pro

2025-01-21 05:23 UTC, samuel-YH approved these changes

2025-02-11 12:27 UTC, Talhasaleem110 approved these changes

2025-09-11 20:58 UTC, asrmGMZ9 commented
<blockquote class="tiktok-embed" cite="https://www.tiktok.com/@absdrive908/video/7534391538084875538" data-video-id="7534391538084875538" data-embed-from="embed_page" style="max-width:605px; min-width:325px;"> <section> <a target="_blank" title="@absdrive908" href="https://www.tiktok.com/@absdrive908?refer=embed">@absdrive908</a> <p>NEYMAR 🤣🤙 </p> <a target="_blank" title="♬ suara asli - ~6~6~6~6~ - JOGASONI⚽📡" href="https://www.tiktok.com/music/suara-asli-6666-7534391566031522577?refer=embed">♬ suara asli - ~6~6~6~6~ - JOGASONI⚽📡</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>